### ISSUE TITLE
Avoid using `now`.

### ISSUE THREAD

**Issue by ilyakmet** [MyWishPlatform/token_saver#2]
`now` is an alias for block.timestamp. 
Both the timestamp and the block hash can be influenced by miners to some extent.

https://github.com/MyWishPlatform/token_saver/blob/f1e5858c23d8035b4ad4907bfc4dffd60088382d/contracts/TokenSaver.sol#L38

https://github.com/MyWishPlatform/token_saver/blob/f1e5858c23d8035b4ad4907bfc4dffd60088382d/contracts/TokenSaver.sol#L79

**Solhint**: [not-rely-on-time](https://github.com/protofire/solhint/blob/master/docs/rules/security/not-rely-on-time.md)

**Comment by wadguk** [comment]
Thank you for your suggestion.
This is only an issue if you need the time to be precise, if you care about long time scales where precise timing is unimportant then 'now' is perfectly fine.
